ng generate	component	navbar
ng generate	component	sidebarl
ng generate	component	sidebarr
ng generate	component	login
ng generate	component	dashboard
ng generate	component	vitality
ng generate	component	vitality-item
ng generate	component	services
ng generate	component	service-item
ng generate	component	otp
ng generate	component	templates
ng generate	component	template-item
ng generate	component	trace
ng generate	component	trace-item
ng generate	component	page-not-found
ng generate	component	configcntrl
ng generate	component	config-item
ng generate	component	server-select
ng generate	guard	qa
ng generate	guard	kav2
ng generate	guard	production
ng generate	guard	product
ng generate	guard	tst
ng generate	service	auth
ng generate	service	options
ng generate	service	backend
ng generate	service	http-request-interceptor

